## Server Properties
server.port=8080
server.compression.enabled=true
server.servlet.context-path=/data-in-cloud
server.error.include-stacktrace=never
logging.pattern.dateformat=
# MongoDB Configuration
spring.data.mongodb.uri=${DB_URL}
# Spring Docker Properties
spring.docker.compose.file=./backend/docker-compose.yml
# Jackson Properties
spring.jackson.serialization.fail-on-empty-beans=false
## Spring Security Properties
app.jwt.secret=esp+AzYn8VKr/p/68fCqwQUjngkSxXBFfP6h8dFcGcv24PlukD4r0f5AyoF3OrHx